"""
RepoLens graph schema — FROZEN after Phase 0.

Do not edit this file after the team signs off in Phase 0 without a
group discussion. Every phase (parser, graph engine, AI, frontend)
codes against these exact shapes.

Serialization note: Node/Edge are dataclasses on the Python side, but
everything crossing a process boundary (fixture JSON, API responses)
uses the plain-dict form shown in fixtures/sample_graph.json — see
to_dict()/from_dict() below for the mapping.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any


class NodeType(str, Enum):
    FILE = "FILE"
    CLASS = "CLASS"
    FUNCTION = "FUNCTION"
    MODULE = "MODULE"
    API_ROUTE = "API_ROUTE"
    EXTERNAL_SERVICE = "EXTERNAL_SERVICE"
    TEST = "TEST"
    CONFIG = "CONFIG"


class EdgeType(str, Enum):
    IMPORTS = "IMPORTS"
    CALLS = "CALLS"
    INHERITS = "INHERITS"
    DEFINES = "DEFINES"   # a FILE node DEFINES a FUNCTION/CLASS node
    TESTS = "TESTS"       # a TEST node TESTS a FUNCTION/CLASS node
    EXPOSES = "EXPOSES"   # a FILE node EXPOSES an API_ROUTE node


@dataclass
class Node:
    id: str                 # globally unique, human-readable: "file_path::qualified_name"
    type: NodeType
    name: str                # short display name, e.g. "process_payment"
    file: str                 # relative path from repo root, e.g. "services/payment.py"
    line_start: int
    line_end: int
    metadata: dict[str, Any] = field(default_factory=dict)
    # metadata conventions (all optional, populate what you can):
    #   "docstring": str
    #   "signature": str            e.g. "process_payment(user_id: int) -> Payment | None"
    #   "decorators": list[str]     e.g. ["@app.post('/payment')"]

    def to_dict(self) -> dict:
        d = asdict(self)
        d["type"] = self.type.value
        return d

    @staticmethod
    def from_dict(d: dict) -> "Node":
        return Node(
            id=d["id"],
            type=NodeType(d["type"]),
            name=d["name"],
            file=d["file"],
            line_start=d["line_start"],
            line_end=d["line_end"],
            metadata=d.get("metadata", {}),
        )


@dataclass
class Edge:
    source: str              # Node.id
    target: str               # Node.id
    type: EdgeType
    metadata: dict[str, Any] = field(default_factory=dict)
    # metadata conventions:
    #   "call_site_line": int   for CALLS edges — which line in `source` makes the call

    def to_dict(self) -> dict:
        d = asdict(self)
        d["type"] = self.type.value
        return d

    @staticmethod
    def from_dict(d: dict) -> "Edge":
        return Edge(
            source=d["source"],
            target=d["target"],
            type=EdgeType(d["type"]),
            metadata=d.get("metadata", {}),
        )


# ---- ID convention (write this on the whiteboard too) ----
#
# FILE nodes:      id == file path, e.g. "services/payment.py"
# everything else: id == f"{file_path}::{qualified_name}"
#   FUNCTION:       "services/payment.py::process_payment"
#   CLASS method:   "services/payment.py::PaymentService.charge"
#   CLASS:          "services/payment.py::PaymentService"
#   API_ROUTE:      "api/routes.py::POST /payment"
#   EXTERNAL_SERVICE: just the service name, no file, e.g. "stripe"
#   TEST:           "tests/test_payment.py::test_process_payment_success"
#
# Unresolved calls (per blueprint §4) simply produce no edge — never a
# dangling edge pointing at a nonexistent node id.
